import { UIConf } from "../ui/UIManager"

export enum UIID {
    Login,
    Hall,
    loading,
    Toast,
    EveryDayTask,
    EveryDayDaKa,
    ShopManager,
    RenovationItemDetail,
    CaipuItemDetail,
    ChuniangDetail,
    UserInfo,
    UserWebView,
    Help,
    ShareHis,
    NewGuide,
    Alert,
    AlertDouble,
    AlertTeshuKeren,
    AlertGetIncome,
    AlertChiHuoJie,
    AlertAutoFuWu,
    AlertClearTable,
    AlertGuide,
    AlertDakaguize,
    AlertShopUpLvlRedPack,
    AlertShopUpReward,
    AlertWallet,
    AlertShopUpLvl,
    AlertQuickKeren,
    AlertShopStart,
    AlertWalletHis,
    AlertGuanfangtixian,
    AlertShareFill,
    AlertShuoyiShuoming,
    AlertShareTixian,
    AlertXieyi,
    AlertAgeLimit,
    Screenshot,
    AlertAlipayAccountFill,
    AlertUserRealAuth,
    AlertTransferRecords,
}

export let UIConfig: { [key: number]: UIConf } = {
    [UIID.Login]: { prefab: "prefab/Login/Login" },
    [UIID.Hall]: { prefab: "prefab/Hall/Hall" },
    [UIID.Toast]: { prefab: "prefab/Toast/Toast" },
    [UIID.EveryDayTask]: { prefab: "prefab/Task/EveryDayTask" },
    [UIID.EveryDayDaKa]: { prefab: "prefab/Task/EveryDayDaKa" },
    [UIID.ShopManager]: { prefab: "prefab/ShopManager/ShopManager" },
    [UIID.RenovationItemDetail]: { prefab: "prefab/ShopManager/RenovationItemDetail" },
    [UIID.CaipuItemDetail]: { prefab: "prefab/ShopManager/CaipuItemDetail" },
    [UIID.ChuniangDetail]: { prefab: "prefab/ShopManager/ChuniangDetail" },
    [UIID.UserInfo]: { prefab: "prefab/UserInfo/UserInfo" },
    [UIID.UserWebView]: { prefab: "prefab/UserInfo/UserWebView" },
    [UIID.Help]: { prefab: "prefab/Alert/Help" },
    [UIID.ShareHis]: { prefab: "prefab/Share/ShareHis" },
    [UIID.NewGuide]: { prefab: "prefab/Alert/NewGuide" },
    [UIID.Alert]: { prefab: "prefab/Alert/Alert" },
    [UIID.AlertDouble]: { prefab: "prefab/Alert/AlertDouble" },
    [UIID.AlertTeshuKeren]: { prefab: "prefab/Alert/AlertTeshuKeren" },
    [UIID.AlertGetIncome]: { prefab: "prefab/Alert/AlertGetIncome" },
    [UIID.AlertChiHuoJie]: { prefab: "prefab/Alert/AlertChiHuoJie" },
    [UIID.AlertAutoFuWu]: { prefab: "prefab/Alert/AlertAutoFuWu" },
    [UIID.AlertClearTable]: { prefab: "prefab/Alert/AlertClearTable" },
    [UIID.AlertGuide]: { prefab: "prefab/Alert/AlertGuide" },
    [UIID.AlertDakaguize]: { prefab: "prefab/Alert/AlertDakaguize" },
    [UIID.AlertShopUpLvlRedPack]: { prefab: "prefab/Alert/AlertShopUpLvlRedPack" },
    [UIID.AlertShopUpReward]: { prefab: "prefab/Alert/AlertShopUpReward" },
    [UIID.AlertWallet]: { prefab: "prefab/Alert/AlertWallet" },
    [UIID.AlertShopUpLvl]: { prefab: "prefab/Alert/AlertShopUpLvl" },
    [UIID.AlertQuickKeren]: { prefab: "prefab/Alert/AlertQuickKeren" },
    [UIID.AlertShopStart]: { prefab: "prefab/Alert/AlertShopStart" },
    [UIID.AlertWalletHis]: { prefab: "prefab/Alert/AlertWalletHis" },
    [UIID.AlertGuanfangtixian]: { prefab: "prefab/Alert/AlertGuanfangtixian" },
    [UIID.AlertShareFill]: { prefab: "prefab/Alert/AlertShareFill" },
    [UIID.AlertShuoyiShuoming]: { prefab: "prefab/Alert/AlertShuoyiShuoming" },
    [UIID.AlertShareTixian]: { prefab: "prefab/Alert/AlertShareTixian" },
    [UIID.AlertXieyi]: { prefab: "prefab/Alert/AlertXieyi" },
    [UIID.AlertAgeLimit]: { prefab: "prefab/Alert/AlertAgeLimit" },
    [UIID.Screenshot]: { prefab: "prefab/Screenshot/Screenshot" },
    [UIID.AlertAlipayAccountFill]: { prefab: "prefab/Alert/AlertAlipayAccountFill" },
    [UIID.AlertUserRealAuth]: { prefab: "prefab/Alert/AlertUserRealAuth" },
    [UIID.AlertTransferRecords]: { prefab: "prefab/Alert/AlertTransferRecords" },
}